import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies, draftMode } from "next/headers";
import { ViewportProvider } from "@/context/viewport";
import { getIsSsrMobile } from "@/context/isMobile";
import { keystaticReader } from "@/lib/reader";
import { getDomain } from "@/lib/domain";
import { GoogleAnalytics } from "@next/third-parties/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export async function generateMetadata(): Promise<Metadata> {
  const domain = await getDomain();
  const settings = await (await keystaticReader()).singletons.settings.read();
  return {
    metadataBase: new URL(domain),
    title: {
      default: settings?.site.title || "",
      template: `%s ${settings?.site.title && `| ${settings?.site.title}`}`,
    },
    // icons: {
    //   apple: "/favicon/apple-touch-icon.png",
    //   icon: ["/favicon/favicon-16x16.png", "/favicon/favicon-32x32.png"],
    //   shortcut: "/favicon/favicon.ico",
    // },
    // manifest: "/favicon/site.webmanifest",
    description: settings?.site.summary,
    openGraph: {
      title: settings?.site.title,
      description: settings?.site.summary,
      url: domain,
      siteName: settings?.site.title,
      locale: "en_US",
      type: "website",
    },
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    twitter: {
      title: settings?.site.title,
      card: "summary_large_image",
    },
    verification: {
      // google: "eZSdmzAXlLkKhNJzfgwDqWORghxnJ8qR9_CHdAh5-xw",
      // yandex: "14d2e73487fa6c71",
    },
  };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isEnabled } = await draftMode();
  const c = await cookies();
  const isMobile = await getIsSsrMobile();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <GoogleAnalytics gaId="G-WWDGEFGSWL" />
        <ViewportProvider isMobile={isMobile}>
          <svg className="pointer-events-none absolute cursor-none h-0">
            <filter id="grainy">
              <feTurbulence
                type="turbulence"
                baseFrequency="0.5"
              ></feTurbulence>
              <feColorMatrix type="saturate" values="0"></feColorMatrix>
            </filter>
          </svg>
          {children}
          {isEnabled && (
            <div>
              Draft mode ({c.get("ks-branch")?.value}){" "}
              <form method="POST" action="/preview/end">
                <button>End preview</button>
              </form>
            </div>
          )}
        </ViewportProvider>
      </body>
    </html>
  );
}
